# Generated by Django 6.0.2 on 2026-03-05 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtarea',
            name='fecha_objetivo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subtarea',
            name='horas_estimadas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
