# Generated by Django 6.0.2 on 2026-03-13 00:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_subtarea_fecha_objetivo_subtarea_horas_estimadas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='tipo',
            field=models.CharField(choices=[('tarea', 'Tarea'), ('proyecto', 'Proyecto'), ('examen', 'Examen'), ('quiz', 'Quiz'), ('laboratorio', 'Laboratorio'), ('lectura', 'Lectura'), ('otro', 'Otro')], default='tarea', max_length=20),
        ),
        migrations.AddField(
            model_name='actividad',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subtarea',
            name='tipo',
            field=models.CharField(choices=[('investigacion', 'Investigación'), ('redaccion', 'Redacción'), ('programacion', 'Programación'), ('estudio', 'Estudio'), ('revision', 'Revisión'), ('practica', 'Práctica'), ('otro', 'Otro')], default='otro', max_length=20),
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limite_diario_horas', models.DecimalField(decimal_places=1, default=6.0, help_text='Límite máximo de horas planificadas por día', max_digits=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
