# Generated by Django 6.0.2 on 2026-04-24 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_actividad_tipo_actividad_usuario_subtarea_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='completada',
            field=models.BooleanField(default=False),
        ),
    ]
