# Generated by Django 6.0.2 on 2026-05-07 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_actividad_completada'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtarea',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('hecha', 'Hecha'), ('pospuesta', 'Pospuesta')], default='pendiente', help_text='Estado actual de la subtarea: pendiente, hecha o pospuesta', max_length=20),
        ),
        migrations.AddField(
            model_name='subtarea',
            name='nota',
            field=models.TextField(blank=True, default='', help_text='Nota opcional (usada principalmente al posponer)'),
        ),
    ]
